#!/usr/bin/nft -f

destroy table inet filter
table inet filter {
  chain input {
    type filter hook input priority filter
    policy drop

    ct state invalid drop comment "early drop of invalid connections"

    ct state {established, related} accept comment "allow tracked connections"

    iif lo accept comment "allow from loopback"

    icmp type destination-unreachable accept
    icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem } accept

    pkttype host limit rate 5/second counter reject with icmpx type admin-prohibited

    counter
  }

  chain forward {
    type filter hook forward priority filter
    policy drop
  }
}
